hmcts/chart-function

.github/workflows/release-drafter.yml, .gitignore, README.md, azure-pipelines.yaml, ci-values.yaml, function/.helmignore, function/Chart.yaml, function/templates/deployment.yaml, function/values.yaml
=> Add basic helm chart for function app

function/Chart.yaml
=> Bump library

README.md, ci-values.yaml, function/Chart.yaml, function/templates/ScaledObject.yaml, function/templates/deployment.yaml, function/values.yaml
=> Adding Keda scaled object to function app

README.md, azure-pipelines.yaml, ci-values-blob.yaml, ci-values-servicebus.yaml, function/templates/ScaledObject.yaml, function/values.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[X] No
```
=> Adds support for Azure Blob Storage Trigger

README.md, function/templates/ScaledObject.yaml, function/values.yaml
=> Adds support for Pod Identity Auth for Blob Storage Trigger

function/Chart.yaml, function/templates/ScaledObject.yaml, function/templates/secretproviderclass.yaml
=> Upgrade Library

function/values.yaml
=> Fix default restartpolicy

ci-values-blob.yaml, function/templates/_blob-trigger.yaml, function/values.yaml
=> Template the storage account name

function/templates/_blob-trigger.yaml
=> Adds defaults for blob trigger now that it isn't supplied in values.yaml

README.md, azure-pipelines.yaml, ci-values-blob-release-name.yaml, ci-values-blob.yaml, function/templates/TriggerAuthentication.yaml, function/templates/_blob-trigger.yaml, function/templates/_template-auth-name.yaml, function/values.yaml
=> Adds dynamic name for trigger auth

README.md, ci-values-blob-release-name.yaml, ci-values-blob.yaml, ci-values-mixed.yaml, ci-values-servicebus.yaml, function/templates/ScaledJob.yaml, function/templates/ScaledObject.yaml, function/templates/TriggerAuthentication.yaml
Add Scaled Object
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Add Scaled Object

.github/renovate.json, function/Chart.yaml, renovate.json
https://tools.hmcts.net/jira/browse/DTSPO-12024
Update helm repo to enable renovate to update chart dependencies
```
[ ] Yes
[x] No
```
=> DTSPO-12024 - Update helm repo

README.md, azure-pipelines.yaml, ci-values-azure-pipelines.yaml, function/templates/ScaledJob.yaml, function/templates/ScaledObject.yaml, function/templates/_azure-pipelines-trigger.yaml
=> Add Azure devops pipeline trigger

function/templates/ScaledJob.yaml, function/values.yaml
=> Add rollout strategy for scaled job

ci-values-azure-pipelines.yaml, function/templates/_azure-pipelines-trigger.yaml
=> pool name is optional, currently failing when trying to quote nil

README.md, azure-pipelines.yaml, ci-values-postgres.yaml, function/templates/ScaledJob.yaml, function/templates/ScaledObject.yaml, function/templates/_postgres-trigger.yaml, function/values.yaml
https://tools.hmcts.net/jira/browse/DMP-107
Adding the postgres trigger for use in DARTS
Exposing the `scalingStrategy` so it can be changed if required.
```
[ ] Yes
[x] No
```
=> Adding postgres trigger

function/templates/_postgres-trigger.yaml
N/A
- it should be "postgresql"
```
[ ] Yes
[ ] No
```
=> Fixing postgres trigger type

function/values.yaml
=> Default to workload idenityt

function/values.yaml
=> Fix level for triggerPodIdentityProvider

README.md, ci-values-azure-pipelines.yaml, function/templates/ScaledJob.yaml, function/templates/TriggerAuthentication.yaml, function/templates/_azure-pipelines-trigger.yaml, function/values.yaml
[DTSPO-13833](https://tools.hmcts.net/jira/browse/DTSPO-13833)
Making changes to allow keda to use manage identity
=> DTSPO-13833 Updating helm chart for azure dev-ops agent to use managed identity

function/values.yaml
Updating values file to set scaleType to the correct casing based on template requirement
=> Updating values file to set scaleType to the correct casing based on template requirement

ci-values-postgres.yaml, function/templates/_postgres-trigger.yaml
Added support for additional postgres connection details as outlined in https://keda.sh/docs/2.16/scalers/postgresql/
=> Added additional alternative arguments for postgres trigger
